name: Deploy Docs
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

on:
  workflow_dispatch:
    inputs:
      deploy_mode:
        description: 'Mode'
        type: choice
        options: ['dev', 'prod']
        required: false
        default: 'dev'
      deploy_docs:
        description: 'Documentation'
        type: boolean
        required: false
        default: true
      deploy_storybook:
        description: 'Storybook'
        type: boolean
        required: false
        default: true

  workflow_call:
    inputs:
      deploy_mode:
        description: 'Mode'
        type: string
        required: false
        default: 'dev'
      deploy_docs:
        description: 'Documentation'
        type: boolean
        required: false
        default: true
      deploy_storybook:
        description: 'Storybook'
        type: boolean
        required: false
        default: true

jobs:
  deploy_docs:
    if: ${{ github.event.inputs.deploy_docs == 'true' }}
    name: Deploy-Docs
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_DOCS_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Printout
        uses: ./.github/actions/printout

      - name: Setup
        uses: ./.github/actions/setup

      - name: Deploy
        uses: ./.github/actions/deploy-docs
        with:
          mode: ${{ github.event.inputs.deploy_mode }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          app_dir: ./apps/docs

  deploy_storybook:
    if: ${{ github.event.inputs.deploy_storybook == 'true' }}
    name: Deploy-Storybook
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_STORYBOOK_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Printout
        uses: ./.github/actions/printout

      - name: Setup
        uses: ./.github/actions/setup

      - name: Deploy
        uses: ./.github/actions/deploy-docs
        with:
          mode: ${{ github.event.inputs.deploy_mode }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          app_dir: ./apps/storybook
