name: Quality-Check

on:
  pull_request:
    branches: [main]

  workflow_call:

jobs:
  quality_check:
    name: Quality-Check
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint
        run: pnpm lint

      - name: Format Check
        run: pnpm format

      - name: Build
        run: pnpm build

      - name: Test - UI Library
        run: pnpm --filter "@ds-starter/ui" test
